### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by Itay4**

### CODE REVIEW

**Comment by avidan-H** [comment]
Thank you for your contribution. Your generosity and caring are unrivaled! Rest assured - our content wizard @ronykoz will very shortly look over your proposed changes.

**Comment by ronykoz** [comment]
@avidan-H is it intentional that the bot will send msgs on your behalf? 
It will spam you with all the corespondents from all the issues

**Comment by avidan-H** [comment]
lol. @ronykoz I'm just testing it right now in one of my own repos using my own user instead of the github user we are planning on making to act as the bot

**Comment by avidan-H** [comment]
These reminders don't seem to be working and the issue is getting pretty stale - @avidan-H - consider whether this PR is still relevant or should be closed.

**Comment by Itay4** [comment]
what.. @ronykoz suppose to consider..

**Comment by avidan-H** [comment]
@Itay4 - birthing pains man. giving birth to a shiny new bot is... well it's only to be expected that there are kinks to be worked out. You'll know when it's ready cause I'll announce myself as a proud new babymama

**Comment by Itay4** [comment]
i think you're still drunk from yesterday..

**Comment by avidan-H** [comment]
This PR is starting to get a little stale and possibly even a little moldy and smelly. @None are there any changes you wanted to make since @Itay4's last comment?

**Comment by Itay4** [comment]
@None ???

**Comment by avidan-H** [comment]
This PR is starting to get a little stale and possibly even a little moldy and smelly. @None are there any changes you wanted to make since @Itay4's last comment?

**Comment by avidan-H** [comment]
broken robot
image
... just needs a little tlc and then he'll be good as new

**Pull request closed without merging**
